spring.datasource.url=${DEMO_DB_URL}
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.api-docs.enabled=true 
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.docker.compose.enabled=false


server.port=8190
jwt.secret=BenimSuperGizliAnahtarim256BitlikOlmali1234567890!


spring.jmx.enabled=false
management.endpoints.jmx.exposure.exclude=*


jwt.expiration=36000000